{
 "title": "Nomad Clients",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Allocation Logs",
   "type": "logs",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{filename!~\"/nomad/alloc/.+/alloc/logs/(loki.+|traefik.+|prometheus.+|connect-proxy.+|promtail.+)\", job=\"nomad\"}",
     "legendFormat": "{{hostname}}"
    },
    {}
   ]
  },
  {
   "title": "Host CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    { "expr": "nomad_client_host_cpu_total", "legendFormat": "{{node_id}} ({{cpu}})" }
   ]
  },
  {
   "title": "Host CPU Idle",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    { "expr": "nomad_client_host_cpu_idle", "legendFormat": "{{node_id}} ({{cpu}})" }
   ]
  },
  {
   "title": "Host Memory Used",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "expr": "nomad_client_host_memory_used", "legendFormat": "{{node_id}}" }
   ]
  },
  {
   "title": "Allocated Disk",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    { "expr": "nomad_client_allocated_disk", "legendFormat": "{{ node_id }}" }
   ]
  },
  {
   "title": "Allocations Running",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nomad_client_allocations_running",
     "legendFormat": "{{ node_id }}"
    }
   ]
  },
  {
   "title": "Client Allocated Memory",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    { "expr": "nomad_client_allocated_memory", "legendFormat": "{{ node_id }}" }
   ]
  },
  {
   "title": "Client Allocated CPU",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "MHz", "label": "MHz" }
   ],
   "targets": [
    { "expr": "nomad_client_allocated_cpu", "legendFormat": "{{ node_id }}" }
   ]
  }
 ]
}